export enum DELIVERY_METHODS {
  UPON_DELIVERY = "UPON_DELIVERY",
  HOME_DELIVERY = "HOME_DELIVERY",
}

export enum ORDER_STATES {
  ACTIVE = "ACTIVE",
  PREPARING = "PREPARING",
  FINISHED = "FINISHED",
  DELIVERING = "DELIVERING",
  DELIVERED = "DELIVERED",
  CANCELED = "CANCELED",
}
